[package]
name = "fc-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "filecustomizer"
path = "src/main.rs"

[dependencies]
fc-core = { path = "../core" }
serde_json.workspace = true

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]

[lints]
workspace = true
