[package]
name = "fc-elevated-helper"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "filecustomizer-elevated"
path = "src/main.rs"

[dependencies]
fc-core = { path = "../core" }
serde_json.workspace = true

[lints]
workspace = true
