// État simulé du backend Tauri, partagé par le banc de test (mock.html) et les scénarios (scenarios.html).
// `window.__saved` reçoit la dernière configuration envoyée à `save_config`, `window.__calls` toutes les commandes.
const none = null;
const state = { config: {version:1, general:{}, navigation_pane:{home:'default',gallery:'default',nodes:{}}, quick_access:{mode:'default',whitelist:[],show_frequent:none,show_recent:none}, this_pc:{hide_folders:[],show_folders:[],hide_drives:[]}, explorer_view:{show_file_extensions:none,show_hidden_files:none,show_system_files:none,launch_to:none,use_checkboxes:none,nav_show_all_folders:none,nav_expand_to_current_folder:none,sync_provider_notifications:none,compact_mode:none,show_status_bar:none,hide_drives_with_no_media:none}, context_menu:{classic_menu:false,blocked_extensions:[],disabled_verbs:[]}, profiles:{Minimal:{navigation_pane:{home:'hide',gallery:'hide',nodes:{}},quick_access:none,this_pc:none,explorer_view:none,context_menu:none}}, rules:[{when:{drive_present:none,drive_absent:'D'},profile:'Minimal'}]},
 config_raw:'version = 1\n', config_path:String.raw`C:\Users\pourm\AppData\Roaming\ExplorerBender\config.toml`, config_error:none, windows_build:26200, daemon_running:true, suspended:false, profile:'Minimal', profile_manual:false, profile_warning:none,
 nodes:[{clsid:'{f874310e-b6b7-47dc-bc84-b9e6b38f5903}',name:'Accueil',effective:1,override:none},{clsid:'{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}',name:'Galerie',effective:1,override:none},{clsid:'{679f85cb-0220-4080-b29b-5540cc05aab6}',name:'Accès rapide',effective:1,override:none},{clsid:'{105FEB6F-4195-4140-B5BB-1FBDCB984AA1}',name:'Proton Drive',effective:1,override:1},{clsid:'{031E4825-7B94-4dc3-B131-E946B44C8DD5}',name:'Bibliothèques',effective:0,override:none}],
 drives:[{letter:'A',kind:'fixe',label:''},{letter:'C',kind:'fixe',label:''},{letter:'D',kind:'fixe',label:''},{letter:'E',kind:'fixe',label:''}],
 extensions:[{clsid:'{a6595cd1-bf77-430a-a452-18696685f7c7}',name:'Adobe.Acrobat.ContextMenu',blocked:false},{clsid:'{<img src=x onerror=alert(1)>}',name:'<b>injection</b>',blocked:false}],
 verbs:[String.raw`Directory\shell\cmd`,String.raw`Directory\shell\find`], folders:[{id:'desktop',label:'Bureau'},{id:'videos',label:'Vidéos'},{id:'3d-objects',label:'Objets 3D'}],
 status:{conflicts:[String.raw`HKCU\Software\Classes\CLSID\{105FEB6F}\System.IsPinnedToNameSpaceTree`],last_apply_at:'2026-10-03T14:01:15Z',last_changes:[{kind:'Applied',what:'Accueil : masqué',detail:''},{kind:'Applied',what:'Épingle « GitHub »',detail:''},{kind:'Skipped',what:'Ce PC : dossiers',detail:''}]}, compat:[] };
window.__saved = null;
window.__calls = [];
window.__TAURI__ = { core: { invoke: async (c,a) => { window.__calls.push([c,a]); if (c==='get_state') return JSON.parse(JSON.stringify(state)); if (c==='save_config'){ window.__saved=a.config; state.config=a.config; return; } return {code:0,output:'ok '+c+' '+JSON.stringify(a)}; } } };
